site_name: Application Documentation

nav:
  - Home: landing.md
  - MongoDB: mongo_setup.md
  - Python: python_setup.md
  - App Setup: local_setup.md
  - App Usage: application_usage.md

theme:
  name: readthedocs
